project:
  type: website
  render:
    - about.qmd
    - blog.qmd
    - index.qmd
    - notebooks/cfa_compared_to_non_cfa.ipynb
    
website: 
  navbar: 
    left:
      - href: index.qmd
      - href: blog.qmd
      - href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true