project:
  type: website
  output-dir: docs
  render:
    - notebooks/cfa_compared_to_non_cfa.ipynb
    
website: 
  navbar:
    background: primary
    search: true
  search: 
    location: navbar
    type: textbox     
format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true