from .data_retrieval import get_data_from_imf

CFA_FRANC_ZONE = [
    "Benin",
    "Burkina Faso",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Congo, Republic of ",
    "Côte d'Ivoire",
    "Equatorial Guinea",
    "Gabon",
    "Guinea-Bissau",
    "Mali",
    "Niger",
    "Senegal",
    "Togo",
]

NON_CFA_CHUNK_1 = [
    "Algeria",
    "Botswana",
    "Burundi",
    "Cabo Verde",
    "Comoros",
    "Djibouti",
    "Egypt",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gambia, The",
    "Ghana",
    "Guinea",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nigeria",
    "Rwanda",
]

NON_CFA_CHUNK_2 = [
    "São Tomé and Príncipe",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan, Republic of",
    "Sudan",
    "Tanzania",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe",
    "Angola",
    "Congo, Dem. Rep. of the",
]
